#!/usr/bin/env python3
"""Bake short neural Yes clips for Wondral Words.

Run from the repo root (not on the phone, not at app runtime):

    python3 scripts/generate-yes-clips.py
    python3 scripts/generate-yes-clips.py --tier 1

Uses Microsoft Edge neural TTS (en-US-JennyNeural) at generation time only.
Clips ship as static mp3s; a correct recall never calls a TTS API.
Phrase matches `successLine` in src/core/deckFlow.ts: "Yes — Bio means life."
"""

from __future__ import annotations

import argparse
import asyncio
import re
import subprocess
import sys
from pathlib import Path

try:
    import edge_tts
except ImportError:
    sys.stderr.write("Install edge-tts first: pip3 install edge-tts\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src" / "data" / "roots.data.ts"
OUT_DIR = ROOT / "public" / "audio" / "yes"
MANIFEST = ROOT / "src" / "core" / "yesClips.ts"

VOICE = "en-US-JennyNeural"
RATE = "-12%"
# Drop leading / trailing pad only — keep the pause after "Yes".
TRIM_AF = (
    "silenceremove=start_periods=1:start_silence=0.05:start_threshold=-35dB,"
    "areverse,"
    "silenceremove=start_periods=1:start_silence=0.12:start_threshold=-35dB,"
    "areverse"
)
ROW = re.compile(
    r"\{\s*t:(\d+)\s*,\s*root:'([^']+)'\s*,\s*say:'([^']+)'\s*,"
    r"\s*org:'[^']+'\s*,\s*mean:'([^']+)'"
)


def utterance_text(root: str, mean: str) -> str:
    spoken_mean = re.sub(r"\s+", " ", mean).strip()
    return f"Yes — {root} means {spoken_mean}."


def parse_roots() -> list[tuple[int, str, str, str]]:
    text = DATA.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str, str]] = []
    for match in ROW.finditer(text):
        tier = int(match.group(1))
        root = match.group(2)
        mean = match.group(4)
        rows.append((tier, root, mean, root.lower()))
    if not rows:
        raise SystemExit(f"No roots parsed from {DATA}")
    return rows


def write_manifest(ids: list[str]) -> None:
    listed = ",\n".join(f"  '{i}'" for i in ids)
    MANIFEST.write_text(
        f"""/**
 * Root ids that ship a baked Yes clip at `public/audio/yes/{{id}}.mp3`.
 *
 * Regenerated by `scripts/generate-yes-clips.py` — do not hand-edit the set.
 * Correct recall never falls back to Web Speech when an id is missing.
 */
export const YES_CLIP_VOICE = '{VOICE}';

export const YES_CLIP_IDS: ReadonlySet<string> = new Set([
{listed},
]);
""",
        encoding="utf-8",
    )


def compress_mp3(path: Path) -> None:
    tmp = path.with_suffix(".tmp.mp3")
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(path),
            "-codec:a",
            "libmp3lame",
            "-b:a",
            "48k",
            "-ac",
            "1",
            "-af",
            TRIM_AF,
            "-ar",
            "22050",
            str(tmp),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    tmp.replace(path)


async def bake_one(root: str, mean: str, dest: Path, sem: asyncio.Semaphore) -> None:
    text = utterance_text(root, mean)
    async with sem:
        communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
        await communicate.save(str(dest))
    compress_mp3(dest)


async def main() -> None:
    parser = argparse.ArgumentParser(description="Bake neural Yes clips")
    parser.add_argument(
        "--tier",
        type=int,
        action="append",
        help="Only these tiers (repeatable). Default: all catalog roots.",
    )
    parser.add_argument("--force", action="store_true", help="Regenerate existing files")
    args = parser.parse_args()

    rows = parse_roots()
    if args.tier:
        wanted = set(args.tier)
        rows = [r for r in rows if r[0] in wanted]
    if not rows:
        raise SystemExit("No roots matched --tier")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sem = asyncio.Semaphore(4)
    jobs = []
    ids: list[str] = []
    for _tier, root, mean, clip_id in rows:
        ids.append(clip_id)
        dest = OUT_DIR / f"{clip_id}.mp3"
        if dest.exists() and dest.stat().st_size > 500 and not args.force:
            continue
        jobs.append(bake_one(root, mean, dest, sem))

    if jobs:
        print(f"Generating {len(jobs)} clip(s) with {VOICE}…")
        await asyncio.gather(*jobs)
    else:
        print("All requested clips already exist.")

    write_manifest(ids)
    sizes = [p.stat().st_size for p in OUT_DIR.glob("*.mp3")]
    total = sum(sizes)
    print(
        f"Wrote {len(ids)} id(s) to {MANIFEST.relative_to(ROOT)}; "
        f"{len(sizes)} mp3s, {total / 1024:.0f} KB"
    )


if __name__ == "__main__":
    asyncio.run(main())
