#!/usr/bin/env python3
"""Bake short neural hear clips for Wondral Words.

Run from the repo root (not on the phone, not at app runtime):

    python3 scripts/generate-hear-clips.py
    python3 scripts/generate-hear-clips.py --tier 1

Uses Microsoft Edge neural TTS (en-US-JennyNeural) at generation time only.
Clips ship as static mp3s; Hear never calls a TTS API.
"""

from __future__ import annotations

import argparse
import asyncio
import re
import subprocess
import sys
import tempfile
from pathlib import Path

def _edge_tts():
    try:
        import edge_tts
    except ImportError:
        sys.stderr.write("Install edge-tts first: pip3 install edge-tts\n")
        sys.exit(1)
    return edge_tts

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src" / "data" / "roots.data.ts"
OUT_DIR = ROOT / "public" / "audio" / "hear"
MANIFEST = ROOT / "src" / "core" / "hearClips.ts"

VOICE = "en-US-JennyNeural"
RATE = "-12%"
# Keep in lockstep with HEAR_BEAT_PAUSE in src/core/speak.ts.
# Jenny ignores extra periods / ellipses / newlines; the baker splits on this
# mark and inserts HEAR_BEAT_GAP_S of silence so name / sound / letters stay
# separate even when they sound alike (Geo / jee oh).
HEAR_BEAT_PAUSE = "…"
HEAR_BEAT_GAP_S = 0.6
# Drop leading / trailing pad on each beat so the inserted gap is the pause.
BEAT_TRIM_AF = (
    "silenceremove=start_periods=1:start_silence=0.04:start_threshold=-35dB,"
    "areverse,"
    "silenceremove=start_periods=1:start_silence=0.08:start_threshold=-35dB,"
    "areverse,"
    "aformat=sample_fmts=fltp:sample_rates=24000:channel_layouts=mono"
)
ROW = re.compile(r"\{\s*t:(\d+)\s*,\s*root:'([^']+)'\s*,\s*say:'([^']+)'")


# Keep in lockstep with SPEAKABLE_SYLLABLES in src/core/speak.ts.
SPEAKABLE_SYLLABLES = {
    "ag": "agg",
    "awd": "awed",
    "by": "bye",
    "dont": "dahnt",
    "dook": "duke",
    "dy": "dye",
    "ek": "eck",
    "fak": "fack",
    "fil": "fill",
    "fiz": "fizz",
    "floo": "flu",
    "foh": "foe",
    "fohn": "fone",
    "fren": "frenn",
    "gr": "gruh",
    "hy": "high",
    "ih": "ihh",
    "ik": "ick",
    "im": "ihm",
    "jood": "jude",
    "joor": "jure",
    "kak": "cack",
    "kal": "cal",
    "kap": "cap",
    "klood": "clued",
    "kog": "cog",
    "koh": "koe",
    "kon": "con",
    "koz": "kahz",
    "krohm": "chrome",
    "loh": "low",
    "lohk": "loke",
    "moht": "moat",
    "nawt": "naught",
    "nayt": "nate",
    "og": "ogg",
    "om": "ahm",
    "os": "oss",
    "pol": "pahl",
    "poz": "pahz",
    "pree": "pree",
    "proh": "pro",
    "ses": "sess",
    "sfeer": "sphere",
    "siv": "sieve",
    "skohp": "scope",
    "sof": "soff",
    "som": "sahm",
    "soo": "sue",
    "sur": "sir",
    "sy": "sigh",
    "syke": "sike",
    "syne": "sign",
    "tek": "tech",
    "than": "thann",
    "tr": "truh",
    "vohk": "voke",
    "vyt": "vite",
    "yoo": "you",
    "zoh": "zoe",
}


def letter_names(root: str) -> str:
    # Keep in lockstep with letterNames() in src/core/speak.ts.
    return " ".join(f"{ch.upper()}." for ch in root if ch.isalpha())


def speakable_pronunciation(say: str) -> str:
    # Keep in lockstep with speakablePronunciation() in src/core/speak.ts.
    # Lowercase syllables a kid would hear. Hyphens become pauses (spaces).
    spoken = re.sub(r"[·•]", "-", say)
    spoken = re.sub(r"\s+", " ", spoken).strip()
    if not spoken:
        return ""
    parts = []
    for part in re.split(r"[-\s]+", spoken):
        if not part:
            continue
        key = part.lower()
        parts.append(SPEAKABLE_SYLLABLES.get(key, key))
    return " ".join(parts)


def utterance_text(root: str, say: str) -> str:
    # Keep in lockstep with utteranceText() in src/core/speak.ts.
    # `{Root}. … {spoken sound}. … The letters {A. B. C.}` — not raw card say.
    spoken = speakable_pronunciation(say)
    letters = letter_names(root)
    if not spoken:
        return f"{root}. {HEAR_BEAT_PAUSE} The letters {letters}"
    return (
        f"{root}. {HEAR_BEAT_PAUSE} {spoken}. {HEAR_BEAT_PAUSE} The letters {letters}"
    )


def utterance_beats(text: str) -> list[str]:
    return [part.strip() for part in text.split(HEAR_BEAT_PAUSE) if part.strip()]


def parse_roots() -> list[tuple[int, str, str, str]]:
    text = DATA.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str, str]] = []
    for match in ROW.finditer(text):
        tier = int(match.group(1))
        root = match.group(2)
        say = match.group(3)
        rows.append((tier, root, say, root.lower()))
    if not rows:
        raise SystemExit(f"No roots parsed from {DATA}")
    return rows


def write_manifest(ids: list[str]) -> None:
    listed = ",\n".join(f"  '{i}'" for i in ids)
    MANIFEST.write_text(
        f"""/**
 * Root ids that ship a baked hear clip at `public/audio/hear/{{id}}.mp3`.
 *
 * Regenerated by `scripts/generate-hear-clips.py` — do not hand-edit the set.
 * Hear never falls back to Web Speech when an id is missing.
 */
export const HEAR_CLIP_VOICE = '{VOICE}';

export const HEAR_CLIP_IDS: ReadonlySet<string> = new Set([
{listed},
]);
""",
        encoding="utf-8",
    )


def stitch_beats(paths: list[Path], dest: Path) -> None:
    if not paths:
        raise ValueError("no beats to stitch")
    if len(paths) == 1:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(paths[0]),
                "-af",
                BEAT_TRIM_AF,
                "-codec:a",
                "libmp3lame",
                "-b:a",
                "48k",
                "-ac",
                "1",
                "-ar",
                "22050",
                str(dest),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return

    inputs: list[str] = []
    for path in paths:
        inputs.extend(["-i", str(path)])
    parts = [
        f"[{i}:a]{BEAT_TRIM_AF}[a{i}]" for i in range(len(paths))
    ]
    silences = [
        f"anullsrc=r=24000:cl=mono:d={HEAR_BEAT_GAP_S}[s{i}]"
        for i in range(len(paths) - 1)
    ]
    concat_in = ""
    concat_n = 0
    for i in range(len(paths)):
        concat_in += f"[a{i}]"
        concat_n += 1
        if i < len(paths) - 1:
            concat_in += f"[s{i}]"
            concat_n += 1
    filt = ";".join(silences + parts) + f";{concat_in}concat=n={concat_n}:v=0:a=1[out]"
    tmp = dest.with_suffix(".tmp.mp3")
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            *inputs,
            "-filter_complex",
            filt,
            "-map",
            "[out]",
            "-codec:a",
            "libmp3lame",
            "-b:a",
            "48k",
            "-ac",
            "1",
            "-ar",
            "22050",
            str(tmp),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    tmp.replace(dest)


async def _save_beat(text: str, dest: Path, sem: asyncio.Semaphore) -> None:
    edge_tts = _edge_tts()
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            async with sem:
                await edge_tts.Communicate(text, VOICE, rate=RATE).save(str(dest))
            return
        except Exception as error:  # noqa: BLE001 — retry transient Edge TTS drops
            last_error = error
            await asyncio.sleep(1.5 * (attempt + 1))
    raise last_error if last_error else RuntimeError("beat bake failed")


async def bake_one(
    root: str, say: str, dest: Path, sem: asyncio.Semaphore
) -> str:
    text = utterance_text(root, say)
    beats = utterance_beats(text)
    with tempfile.TemporaryDirectory() as tmp:
        paths = []
        for index, beat in enumerate(beats):
            raw = Path(tmp) / f"beat{index}.mp3"
            await _save_beat(beat, raw, sem)
            paths.append(raw)
        stitch_beats(paths, dest)
    return text


async def main() -> None:
    parser = argparse.ArgumentParser(description="Bake neural hear clips")
    parser.add_argument(
        "--tier",
        type=int,
        action="append",
        help="Only these tiers (repeatable). Default: all catalog roots.",
    )
    parser.add_argument("--force", action="store_true", help="Regenerate existing files")
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print every Hear line (id + utterance) and exit.",
    )
    args = parser.parse_args()

    rows = parse_roots()
    if args.tier:
        wanted = set(args.tier)
        rows = [r for r in rows if r[0] in wanted]
    if not rows:
        raise SystemExit("No roots matched --tier")

    if args.list:
        for _tier, root, say, clip_id in rows:
            print(f"- `{clip_id}`: {utterance_text(root, say)}")
        return

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sem = asyncio.Semaphore(4)
    jobs = []
    ids: list[str] = []
    for _tier, root, say, clip_id in rows:
        ids.append(clip_id)
        dest = OUT_DIR / f"{clip_id}.mp3"
        if dest.exists() and dest.stat().st_size > 500 and not args.force:
            continue
        jobs.append(bake_one(root, say, dest, sem))

    if jobs:
        print(f"Generating {len(jobs)} clip(s) with {VOICE}…")
        await asyncio.gather(*jobs)
    else:
        print("All requested clips already exist.")

    # Manifest lists every file we intend to ship for this run, including
    # clips that were already on disk.
    write_manifest(ids)
    sizes = [p.stat().st_size for p in OUT_DIR.glob("*.mp3")]
    total = sum(sizes)
    print(
        f"Wrote {len(ids)} id(s) to {MANIFEST.relative_to(ROOT)}; "
        f"{len(sizes)} mp3s, {total / 1024:.0f} KB"
    )


if __name__ == "__main__":
    asyncio.run(main())
