#!/usr/bin/env python3
"""Bake short neural hear clips for Wondral Words.

Run from the repo root (not on the phone, not at app runtime):

    python3 scripts/generate-hear-clips.py
    python3 scripts/generate-hear-clips.py --tier 1

Uses Microsoft Edge neural TTS (en-US-JennyNeural) at generation time only.
Clips ship as static mp3s; Hear never calls a TTS API.
"""

from __future__ import annotations

import argparse
import asyncio
import re
import subprocess
import sys
from pathlib import Path

try:
    import edge_tts
except ImportError:
    sys.stderr.write("Install edge-tts first: pip3 install edge-tts\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src" / "data" / "roots.data.ts"
OUT_DIR = ROOT / "public" / "audio" / "hear"
MANIFEST = ROOT / "src" / "core" / "hearClips.ts"

VOICE = "en-US-JennyNeural"
RATE = "-12%"
ROW = re.compile(r"\{\s*t:(\d+)\s*,\s*root:'([^']+)'\s*,\s*say:'([^']+)'")


def letter_names(root: str) -> str:
    # Keep in lockstep with letterNames() in src/core/speak.ts.
    return " ".join(f"{ch.upper()}." for ch in root if ch.isalpha())


def utterance_text(root: str, say: str) -> str:
    # Keep in lockstep with utteranceText() in src/core/speak.ts.
    # `{Root}. {say}. The letters {A. B. C.}` — letters from the written root.
    spoken = re.sub(r"[·•]", "-", say)
    spoken = re.sub(r"\s+", " ", spoken).strip()
    letters = letter_names(root)
    if not spoken:
        return f"{root}. The letters {letters}"
    return f"{root}. {spoken}. The letters {letters}"


def parse_roots() -> list[tuple[int, str, str, str]]:
    text = DATA.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str, str]] = []
    for match in ROW.finditer(text):
        tier = int(match.group(1))
        root = match.group(2)
        say = match.group(3)
        rows.append((tier, root, say, root.lower()))
    if not rows:
        raise SystemExit(f"No roots parsed from {DATA}")
    return rows


def write_manifest(ids: list[str]) -> None:
    listed = ",\n".join(f"  '{i}'" for i in ids)
    MANIFEST.write_text(
        f"""/**
 * Root ids that ship a baked hear clip at `public/audio/hear/{{id}}.mp3`.
 *
 * Regenerated by `scripts/generate-hear-clips.py` — do not hand-edit the set.
 * Hear never falls back to Web Speech when an id is missing.
 */
export const HEAR_CLIP_VOICE = '{VOICE}';

export const HEAR_CLIP_IDS: ReadonlySet<string> = new Set([
{listed},
]);
""",
        encoding="utf-8",
    )


def compress_mp3(path: Path) -> None:
    tmp = path.with_suffix(".tmp.mp3")
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(path),
            "-codec:a",
            "libmp3lame",
            "-b:a",
            "48k",
            "-ac",
            "1",
            "-ar",
            "22050",
            str(tmp),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    tmp.replace(path)


async def bake_one(root: str, say: str, dest: Path, sem: asyncio.Semaphore) -> None:
    text = utterance_text(root, say)
    async with sem:
        communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
        await communicate.save(str(dest))
    compress_mp3(dest)


async def main() -> None:
    parser = argparse.ArgumentParser(description="Bake neural hear clips")
    parser.add_argument(
        "--tier",
        type=int,
        action="append",
        help="Only these tiers (repeatable). Default: all catalog roots.",
    )
    parser.add_argument("--force", action="store_true", help="Regenerate existing files")
    args = parser.parse_args()

    rows = parse_roots()
    if args.tier:
        wanted = set(args.tier)
        rows = [r for r in rows if r[0] in wanted]
    if not rows:
        raise SystemExit("No roots matched --tier")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sem = asyncio.Semaphore(4)
    jobs = []
    ids: list[str] = []
    for _tier, root, say, clip_id in rows:
        ids.append(clip_id)
        dest = OUT_DIR / f"{clip_id}.mp3"
        if dest.exists() and dest.stat().st_size > 500 and not args.force:
            continue
        jobs.append(bake_one(root, say, dest, sem))

    if jobs:
        print(f"Generating {len(jobs)} clip(s) with {VOICE}…")
        await asyncio.gather(*jobs)
    else:
        print("All requested clips already exist.")

    # Manifest lists every file we intend to ship for this run, including
    # clips that were already on disk.
    write_manifest(ids)
    sizes = [p.stat().st_size for p in OUT_DIR.glob("*.mp3")]
    total = sum(sizes)
    print(
        f"Wrote {len(ids)} id(s) to {MANIFEST.relative_to(ROOT)}; "
        f"{len(sizes)} mp3s, {total / 1024:.0f} KB"
    )


if __name__ == "__main__":
    asyncio.run(main())
